# Generated by Django 5.1.2 on 2024-10-27 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('keranjang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='sneaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.sneaker'),
        ),
        migrations.DeleteModel(
            name='Sneaker',
        ),
    ]