# Generated by Django 5.1.2 on 2024-10-26 12:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_sneaker_slug'),
        ('keranjang', '0002_purchasehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sneaker',
            old_name='image_url',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sneaker',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='sneaker',
            name='user',
        ),
        migrations.AddField(
            model_name='sneaker',
            name='brand',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sneaker',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sneaker',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='sneaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.sneaker'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
