
# Generated by Django 5.1.2 on 2024-10-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keranjang', '0003_rename_purchasehistory_cartitem_usercart'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='total_harga',
            field=models.IntegerField(default=0),
        ),
    ]
