# Generated by Django 5.1.1 on 2024-10-24 18:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_sneaker_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_description', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.sneaker')),
            ],
        ),
    ]
