<<<<<<< HEAD
# Generated by Django 5.1.1 on 2024-10-24 18:19

import django.db.models.deletion
import uuid
=======
# Generated by Django 5.1.2 on 2024-10-25 16:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
>>>>>>> 9e74df23bcf0cf31dab7e02d81e28a57a4733f71
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_sneaker_image'),
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 9e74df23bcf0cf31dab7e02d81e28a57a4733f71
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_description', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.sneaker')),
=======
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('sneaker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.sneaker')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_description', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.sneaker')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> 9e74df23bcf0cf31dab7e02d81e28a57a4733f71
            ],
        ),
    ]
