# Generated by Django 5.1.2 on 2024-10-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_review_user_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
