# Generated by Django 5.1.2 on 2024-10-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_rating_review_count_rating_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='review',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
