# Generated by Django 5.1.1 on 2024-10-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_sneaker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
