# Generated by Django 5.1.1 on 2024-10-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_sneaker_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]